import numpy as np
from kernels.base import BaseKernel
from scipy.ndimage import binary_fill_holes
from onnx import helper, TensorProto, numpy_helper

class FloodKernel(BaseKernel):
    @property
    def name(self):
        return "color_flood"

    @property
    def parameters(self):
        return 0 # Zero parameters for morphology

    def execute(self, grid, color=1, **kwargs):
        grid = np.array(grid)
        mask = (grid != 0)
        filled_mask = binary_fill_holes(mask)
        new_grid = np.copy(grid)
        new_grid[(filled_mask == 1) & (mask == 0)] = color
        return new_grid

    def to_onnx_nodes(self, input_name, output_name, color=1, precision='float32', **kwargs):
        nodes = []
        initializers = []
        dtype = TensorProto.FLOAT if precision == 'float32' else TensorProto.FLOAT16
        np_dtype = np.float32 if precision == 'float32' else np.float16

        # 1. Isolate the seed color and the boundary
        # For demo simplicity, let's assume Channel 0 is background
        # We need to unroll MaxPool to perform dilation

        current_input = input_name
        for step in range(30):
            pool_out = f'flood_pool_{step}'
            # MaxPool over 3x3 to dilate
            nodes.append(helper.make_node(
                'MaxPool',
                inputs=[current_input],
                outputs=[pool_out],
                kernel_shape=[3, 3],
                pads=[1, 1, 1, 1],
                strides=[1, 1],
                name=f'Flood_Dilation_{step}'
            ))

            # Constrain dilation by boundary mask
            # Note: border_mask is generated by the compiler globally
            masked_out = f'flood_masked_{step}' if step < 29 else output_name
            nodes.append(helper.make_node(
                'Min',
                inputs=[pool_out, 'border_mask'],
                outputs=[masked_out],
                name=f'Flood_Boundary_Constraint_{step}'
            ))
            current_input = masked_out

        return nodes, initializers
